name: bibli_app
description: "Um app para ajudar na leitura e compreensão da Bíblia Sagrada."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.6
  shared_preferences: ^2.2.3
  flutter_dotenv: ^6.0.0
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.0
  badges: ^3.1.2
  percent_indicator: ^4.2.3
  share_plus: ^7.2.2
  just_audio: ^0.9.36
  audio_session: ^0.1.16
  confetti: ^0.7.0
  shimmer: ^3.0.0
  path_provider: ^2.1.4
  http: ^1.2.2
  lottie: ^3.1.2
  package_info_plus: ^8.0.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  mocktail: ^1.0.3
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo/static/Arimo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Arimo/static/Arimo-Bold.ttf
          weight: 700
  assets:
    - .env
    - assets/images/
    - assets/images/signup_and_signin/image.png
    - assets/images/google_logo.png
    - assets/data/
    - assets/reading_plans/
    - assets/images/welcome_sleep_page/
    - assets/images/sleep_page/
    - assets/images/sleep_music_page/
    - assets/images/play_option_page/
    - assets/images/music/
    - assets/images/reading_plans/card_fundo.png
    - assets/images/reading_plans/icon_01.png
    - assets/images/reading_plans/icon_02.png
    - assets/images/reading_plans/icon_03.png
    - assets/images/reading_plans/icon_04.png
    - assets/images/reading_plans/icon_05.png

flutter_native_splash:
  color: "#005954"
  image: assets/images/logo.png
  color_dark: "#005954"
  image_dark: assets/images/logo.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
